name: Test

on: push

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
          check-latest: true
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install bc gcc libgl1-mesa-dev libwayland-dev libx11-dev libxkbcommon-dev xorg-dev xvfb
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test -v ./...
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: '2022.1.1'
